// Code generated by Wire protocol buffer compiler, do not edit.
// Source: OSMPBF.Node in osmformat.proto
package crosby.binary.wire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class Node extends Message<Node, Node.Builder> {
  public static final ProtoAdapter<Node> ADAPTER = new ProtoAdapter_Node();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final Long DEFAULT_LAT = 0L;

  public static final Long DEFAULT_LON = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long id;

  /**
   * Parallel arrays.
   * String IDs.
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.PACKED
  )
  public final List<Integer> keys;

  /**
   * String IDs.
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.PACKED
  )
  public final List<Integer> vals;

  /**
   * May be omitted in omitmeta
   */
  @WireField(
      tag = 4,
      adapter = "crosby.binary.wire.Info#ADAPTER"
  )
  public final Info info;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long lat;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#SINT64",
      label = WireField.Label.REQUIRED
  )
  public final Long lon;

  public Node(Long id, List<Integer> keys, List<Integer> vals, Info info, Long lat, Long lon) {
    this(id, keys, vals, info, lat, lon, ByteString.EMPTY);
  }

  public Node(Long id, List<Integer> keys, List<Integer> vals, Info info, Long lat, Long lon,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.keys = Internal.immutableCopyOf("keys", keys);
    this.vals = Internal.immutableCopyOf("vals", vals);
    this.info = info;
    this.lat = lat;
    this.lon = lon;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.keys = Internal.copyOf(keys);
    builder.vals = Internal.copyOf(vals);
    builder.info = info;
    builder.lat = lat;
    builder.lon = lon;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Node)) return false;
    Node o = (Node) other;
    return unknownFields().equals(o.unknownFields())
        && id.equals(o.id)
        && keys.equals(o.keys)
        && vals.equals(o.vals)
        && Internal.equals(info, o.info)
        && lat.equals(o.lat)
        && lon.equals(o.lon);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + id.hashCode();
      result = result * 37 + keys.hashCode();
      result = result * 37 + vals.hashCode();
      result = result * 37 + (info != null ? info.hashCode() : 0);
      result = result * 37 + lat.hashCode();
      result = result * 37 + lon.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", id=").append(id);
    if (!keys.isEmpty()) builder.append(", keys=").append(keys);
    if (!vals.isEmpty()) builder.append(", vals=").append(vals);
    if (info != null) builder.append(", info=").append(info);
    builder.append(", lat=").append(lat);
    builder.append(", lon=").append(lon);
    return builder.replace(0, 2, "Node{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Node, Builder> {
    public Long id;

    public List<Integer> keys;

    public List<Integer> vals;

    public Info info;

    public Long lat;

    public Long lon;

    public Builder() {
      keys = Internal.newMutableList();
      vals = Internal.newMutableList();
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * Parallel arrays.
     * String IDs.
     */
    public Builder keys(List<Integer> keys) {
      Internal.checkElementsNotNull(keys);
      this.keys = keys;
      return this;
    }

    /**
     * String IDs.
     */
    public Builder vals(List<Integer> vals) {
      Internal.checkElementsNotNull(vals);
      this.vals = vals;
      return this;
    }

    /**
     * May be omitted in omitmeta
     */
    public Builder info(Info info) {
      this.info = info;
      return this;
    }

    public Builder lat(Long lat) {
      this.lat = lat;
      return this;
    }

    public Builder lon(Long lon) {
      this.lon = lon;
      return this;
    }

    @Override
    public Node build() {
      if (id == null
          || lat == null
          || lon == null) {
        throw Internal.missingRequiredFields(id, "id",
            lat, "lat",
            lon, "lon");
      }
      return new Node(id, keys, vals, info, lat, lon, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Node extends ProtoAdapter<Node> {
    public ProtoAdapter_Node() {
      super(FieldEncoding.LENGTH_DELIMITED, Node.class, "type.googleapis.com/OSMPBF.Node", Syntax.PROTO_2, null);
    }

    @Override
    public int encodedSize(Node value) {
      int result = 0;
      result += ProtoAdapter.SINT64.encodedSizeWithTag(1, value.id);
      result += ProtoAdapter.UINT32.asPacked().encodedSizeWithTag(2, value.keys);
      result += ProtoAdapter.UINT32.asPacked().encodedSizeWithTag(3, value.vals);
      result += Info.ADAPTER.encodedSizeWithTag(4, value.info);
      result += ProtoAdapter.SINT64.encodedSizeWithTag(8, value.lat);
      result += ProtoAdapter.SINT64.encodedSizeWithTag(9, value.lon);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, Node value) throws IOException {
      ProtoAdapter.SINT64.encodeWithTag(writer, 1, value.id);
      ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 2, value.keys);
      ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 3, value.vals);
      Info.ADAPTER.encodeWithTag(writer, 4, value.info);
      ProtoAdapter.SINT64.encodeWithTag(writer, 8, value.lat);
      ProtoAdapter.SINT64.encodeWithTag(writer, 9, value.lon);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Node decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.SINT64.decode(reader)); break;
          case 2: builder.keys.add(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: builder.vals.add(ProtoAdapter.UINT32.decode(reader)); break;
          case 4: builder.info(Info.ADAPTER.decode(reader)); break;
          case 8: builder.lat(ProtoAdapter.SINT64.decode(reader)); break;
          case 9: builder.lon(ProtoAdapter.SINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public Node redact(Node value) {
      Builder builder = value.newBuilder();
      if (builder.info != null) builder.info = Info.ADAPTER.redact(builder.info);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
